"""add aguardando_sinais_vitais to patient status enum

Revision ID: 5853aa613ec4
Revises: dedcff81eeee
Create Date: 2026-08-29 15:38:21.903684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5853aa613ec4'
down_revision: Union[str, Sequence[str], None] = 'dedcff81eeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE patient_status_enum ADD VALUE 'aguardando_sinais_vitais'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
