"""add vital signs columns

Revision ID: dedcff81eeee
Revises: fd99da12f452
Create Date: 2026-08-29 15:19:26.792830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedcff81eeee'
down_revision: Union[str, Sequence[str], None] = 'fd99da12f452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('patients', sa.Column('systolic_pressure', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('diastolic_pressure', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('heart_rate', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('oxygen_saturation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'oxygen_saturation')
    op.drop_column('patients', 'heart_rate')
    op.drop_column('patients', 'diastolic_pressure')
    op.drop_column('patients', 'systolic_pressure')
    op.drop_column('patients', 'temperature')
    # ### end Alembic commands ###
